cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'asdf'
brew 'ffmpeg'
brew 'fzf'
brew 'gawk'
brew 'gnupg'
brew 'starship'
brew 'tcl-tk'
brew 'thefuck'
brew 'zlib'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'bettertouchtool'
cask 'bitwarden'
cask 'chatgpt'
cask 'cursor'
cask 'discord'
cask 'ghostty'
cask 'google-chrome'
cask 'microsoft-teams'
cask 'okta-verify'
cask 'onedrive'
cask 'postman'
cask 'slack'
cask 'spotify'
cask 'sublime-merge'
cask 'sublime-text'
cask 'tor-browser'
cask 'whatsapp'
cask 'zoom'
